class GrandmasterPlayer : HereticPlayer
{
    // Player stats
    int GMStrength; property GMStrength : GMStrength;
    int GMMagic; property GMMagic : GMMagic;
    int GMSkill; property GMSkill : GMSkill;
    int GMSpeed; property GMSpeed : GMSpeed;
    int GMLuck; property GMLuck : GMLuck;
    int GMDef; property GMDef : GMDef;
    int GMSwordSkill; property GMSwordSkill : GMSwordSkill;
    int GMTomeSkill; property GMTomeSkill : GMTomeSkill;
    int GMTomeExp; property GMTomeExp : GMTomeExp;
    int GMSwordExp; property GMSwordExp : GMSwordExp;
    int GMSwordType; property GMSwordType : GMSwordType;
    int GMTomeType; property GMTomeType : GMTomeType;
    
    default
	{
		Player.MaxHealth 100;
		Player.Viewheight 48;
		Player.AttackZOffset 14;
		Player.DisplayName "Tactician";
		//Player.StartItem "GMNoSword";
        //Player.StartItem "WWGMTomeUses", 50;
        Player.StartItem "GMBaseSword";
        GrandmasterPlayer.GMStrength 5;
        GrandmasterPlayer.GMMagic 5;
        GrandmasterPlayer.GMSkill 5;
        GrandmasterPlayer.GMSpeed 5;
        GrandmasterPlayer.GMLuck 5;
        GrandmasterPlayer.GMDef 5;
        GrandmasterPlayer.GMSwordType 0;
        GrandmasterPlayer.GMTomeType 0;
    }
    
    /*
    override void Tick()
    {
        if     (GetCvar("wwgm_playersound") == 0) { SoundClass = "RobinM1"; }
        else if(GetCvar("wwgm_playersound") == 1) { SoundClass = "RobinM2"; }
        else if(GetCvar("wwgm_playersound") == 2) { SoundClass = "RobinM3"; }
        else if(GetCvar("wwgm_playersound") == 3) { SoundClass = "RobinF1"; }
        else if(GetCvar("wwgm_playersound") == 4) { SoundClass = "RobinF2"; }
        else if(GetCvar("wwgm_playersound") == 5) { SoundClass = "RobinF3"; }
    return Super.Tick();
    }
    */
}
